package:
  name: pyo3-conda-test
  version: 1.0.0

requirements:
  build:
    - ${{ compiler('rust') }}
    - python
  run:
    - python

source:
  path: .

build:
  script:
    - if: unix
      then:
      - cargo install --locked --bins --root ${PREFIX} --path .

tests:
  - package_contents: { bin: pyo3-conda-test }
  - script: pyo3-conda-test
