package:
  name: pyo3-conda-test
  version: 1.0.0

requirements:
  build:
    - ${{ compiler('rust') }}
    - python
  run:
    - python

source:
  path: .

build:
  script:
    - $BUILD_PREFIX/bin/cargo install --locked --bins --root ${PREFIX} --path .

tests:
  - script:
    - pyo3-conda-test
