package:
  name: pyo3-conda-test
  version: 1.0.0

requirements:
  build:  # runs at build time
    - ${{ compiler('rust') }}
  host:  # what to link against at build time
    - python == 3.13
  run:  # required at runtime
    - python == 3.13

source:
  path: .

build:
  script:
    - cargo install --locked --bins --root ${PREFIX} --path .

tests:
  - package_contents: { bin: pyo3-conda-test }
  - script: pyo3-conda-test
